### ISSUE TITLE
Import error: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by mmgordon82** [ai4ce/pyAprilTag#2]
```
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyAprilTag
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mmgor\AppData\Local\Programs\Python\Python37\lib\site-packages\pyAprilTag\__init__.py", line 2, in <module>
    from pyAprilTag._apriltag import *
ImportError: DLL load failed: The specified module could not be found.
>>>
```

Demo files return the same error.

```
PS C:\Users\mmgor\apriltag> dir -d 3 C:\Users\mmgor\AppData\Local\Programs\Python\Python37\lib\site-packages\pyAprilTag\


    Directory: C:\Users\mmgor\AppData\Local\Programs\Python\Python37\lib\site-packages\pyAprilTag


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/14/2019   3:12 PM                data
d-----       10/14/2019   3:12 PM                __pycache__
-a----       10/14/2019   3:12 PM            140 demo.py
-a----       10/14/2019   3:12 PM            879 demo_calib.py
-a----       10/14/2019   3:12 PM            864 demo_calib_by_photo.py
-a----       10/14/2019   3:12 PM            247 demo_plt.py
-a----       10/14/2019   3:12 PM           1388 vdemo_cv.py
-a----       10/14/2019   3:12 PM           1756 vdemo_plt.py
-a----       10/14/2019   3:12 PM         353792 _apriltag.cp37-win_amd64.pyd
-a----       10/14/2019   3:12 PM            558 __init__.py


    Directory: C:\Users\mmgor\AppData\Local\Programs\Python\Python37\lib\site-packages\pyAprilTag\data


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/14/2019   3:12 PM                calib
-a----       10/14/2019   3:12 PM          70603 calib_pattern_Tag36h11.png


    Directory: C:\Users\mmgor\AppData\Local\Programs\Python\Python37\lib\site-packages\pyAprilTag\data\calib


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       10/14/2019   3:12 PM         544436 AprilCalib_orgframe_00000.png
-a----       10/14/2019   3:12 PM         517178 AprilCalib_orgframe_00001.png
-a----       10/14/2019   3:12 PM         539489 AprilCalib_orgframe_00002.png
-a----       10/14/2019   3:12 PM         527758 AprilCalib_orgframe_00003.png
-a----       10/14/2019   3:12 PM         521976 AprilCalib_orgframe_00004.png
-a----       10/14/2019   3:12 PM         521109 AprilCalib_orgframe_00005.png
-a----       10/14/2019   3:12 PM         524141 AprilCalib_orgframe_00006.png
-a----       10/14/2019   3:12 PM         527113 AprilCalib_orgframe_00007.png
-a----       10/14/2019   3:12 PM         513707 AprilCalib_orgframe_00008.png
-a----       10/14/2019   3:12 PM         516518 AprilCalib_orgframe_00009.png


    Directory: C:\Users\mmgor\AppData\Local\Programs\Python\Python37\lib\site-packages\pyAprilTag\__pycache__


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       10/14/2019   3:12 PM            327 demo.cpython-37.pyc
-a----       10/14/2019   3:12 PM           1160 demo_calib.cpython-37.pyc
-a----       10/14/2019   3:12 PM           1065 demo_calib_by_photo.cpython-37.pyc
-a----       10/14/2019   3:12 PM            469 demo_plt.cpython-37.pyc
-a----       10/14/2019   3:12 PM           1052 vdemo_cv.cpython-37.pyc
-a----       10/14/2019   3:12 PM           1540 vdemo_plt.cpython-37.pyc
-a----       10/14/2019   3:12 PM            414 __init__.cpython-37.pyc

```

OS: Windows 10 Pro Version 64bit	10.0.18362 Build 18362
Python: 3.7.4 64bit
What DLL file does it require?

**Comment by simbaforrest** [comment]
Please try the following:

1. Save the following as opencv_py37_conda-forge.txt

**If you are using windows:**
> ca-certificates=2019.9.11=hecc5488_0
> certifi=2019.6.16=py37_1
> cycler=0.10.0=py_1
> cython=0.29.13=py37h6538335_0
> freetype=2.10.0=h563cfd7_1
> icu=64.2=he025d50_1
> intel-openmp=2019.4=245
> jpeg=9c=hfa6e2cd_1001
> kiwisolver=1.1.0=py37he980bc4_0
> libblas=3.8.0=12_mkl
> libcblas=3.8.0=12_mkl
> liblapack=3.8.0=12_mkl
> liblapacke=3.8.0=12_mkl
> libpng=1.6.37=h7602738_0
> libtiff=4.0.10=h6512ee2_1003
> libwebp=1.0.2=hfa6e2cd_2
> lz4-c=1.8.3=he025d50_1001
> matplotlib=3.1.1=py37_1
> matplotlib-base=3.1.1=py37h2852a4a_1
> mkl=2019.4=245
> numpy=1.17.1=py37hc71023c_0
> opencv=3.4.7=py37hde96b69_2
> openssl=1.1.1c=hfa6e2cd_0
> pip=19.2.3=py37_0
> pyparsing=2.4.2=py_0
> pyqt=5.9.2=py37h6538335_4
> python=3.7.3=h510b542_1
> python-dateutil=2.8.0=py_0
> qt=5.9.7=h506e8af_3
> setuptools=41.2.0=py37_0
> sip=4.19.8=py37h6538335_1000
> six=1.12.0=py37_1000
> sqlite=3.29.0=hfa6e2cd_1
> tornado=6.0.3=py37hfa6e2cd_0
> vc=14.1=h0510ff6_4
> vs2015_runtime=14.16.27012=hf0eaf9b_0
> wheel=0.33.6=py37_0
> wincertstore=0.2=py37_1002
> xz=5.2.4=h2fa13f4_1001
> zlib=1.2.11=h2fa13f4_1006
> zstd=1.4.0=hd8a0e53_0


**If you are using ubuntu:**
> _libgcc_mutex=0.1=main
> blas=1.0=mkl
> bzip2=1.0.8=h516909a_1
> ca-certificates=2019.9.11=hecc5488_0
> cairo=1.16.0=h18b612c_1001
> certifi=2019.9.11=py37_0
> cycler=0.10.0=py37_0
> cython=0.29.13=py37he6710b0_0
> dbus=1.13.6=he372182_0
> expat=2.2.6=he6710b0_0
> ffmpeg=4.1.3=h167e202_0
> fontconfig=2.13.1=he4413a7_1000
> freeglut=3.0.0=hf484d3e_1005
> freetype=2.9.1=h8a8886c_1
> gettext=0.19.8.1=hc5be6a0_1002
> giflib=5.1.9=h516909a_0
> glib=2.58.3=h6f030ca_1002
> gmp=6.1.2=hf484d3e_1000
> gnutls=3.6.5=hd3a4fd2_1002
> graphite2=1.3.13=hf484d3e_1000
> gst-plugins-base=1.14.5=h0935bb2_0
> gstreamer=1.14.5=h36ae1b5_0
> harfbuzz=2.4.0=h37c48d4_1
> hdf5=1.10.5=nompi_h3c11f04_1103
> icu=58.2=h9c2bf20_1
> intel-openmp=2019.4=243
> jasper=1.900.1=h07fcdf6_1006
> jpeg=9c=h14c3975_1001
> kiwisolver=1.1.0=py37he6710b0_0
> lame=3.100=h14c3975_1001
> libblas=3.8.0=12_mkl
> libcblas=3.8.0=12_mkl
> libedit=3.1.20181209=hc058e9b_0
> libffi=3.2.1=hd88cf55_4
> libgcc-ng=9.1.0=hdf63c60_0
> libgfortran=3.0.0=1
> libgfortran-ng=7.3.0=hdf63c60_0
> libglu=9.0.0=hf484d3e_1000
> libiconv=1.15=h516909a_1005
> liblapack=3.8.0=12_mkl
> liblapacke=3.8.0=12_mkl
> libopus=1.3=h7b6447c_0
> libpng=1.6.37=hbc83047_0
> libstdcxx-ng=9.1.0=hdf63c60_0
> libtiff=4.0.10=h57b8799_1003
> libuuid=2.32.1=h14c3975_1000
> libvpx=1.7.0=h439df22_0
> libwebp=1.0.2=h576950b_1
> libxcb=1.13=h1bed415_1
> libxml2=2.9.9=hea5a465_1
> lz4-c=1.8.3=he1b5a44_1001
> matplotlib=3.1.1=py37h5429711_0
> mkl=2019.4=243
> mkl-service=2.3.0=py37he904b0f_0
> mkl_fft=1.0.14=py37ha843d7b_0
> mkl_random=1.0.2=py37hd81dba3_0
> ncurses=6.1=he6710b0_1
> nettle=3.4.1=h1bed415_1002
> numpy=1.16.5=py37h7e9f1db_0
> numpy-base=1.16.5=py37hde5b4d6_0
> opencv=3.4.7=py37h8949d38_2
> openh264=1.8.0=hdbcaa40_1000
> openssl=1.1.1c=h516909a_0
> pcre=8.43=he6710b0_0
> pip=19.2.2=py37_0
> pixman=0.38.0=h516909a_1003
> pyparsing=2.4.2=py_0
> pyqt=5.9.2=py37h05f1152_2
> python=3.7.4=h265db76_1
> python-dateutil=2.8.0=py37_0
> pytz=2019.2=py_0
> qt=5.9.7=h52cfd70_2
> readline=7.0=h7b6447c_5
> scipy=1.3.1=py37h7c811a0_0
> setuptools=41.2.0=py37_0
> sip=4.19.8=py37hf484d3e_0
> six=1.12.0=py37_0
> sqlite=3.29.0=h7b6447c_0
> tk=8.6.8=hbc83047_0
> tornado=6.0.3=py37h7b6447c_0
> wheel=0.33.6=py37_0
> x264=1!152.20180806=h14c3975_0
> xorg-fixesproto=5.0=h14c3975_1002
> xorg-inputproto=2.3.2=h14c3975_1002
> xorg-kbproto=1.0.7=h14c3975_1002
> xorg-libice=1.0.10=h516909a_0
> xorg-libsm=1.2.3=h84519dc_1000
> xorg-libx11=1.6.8=h516909a_0
> xorg-libxau=1.0.9=h14c3975_0
> xorg-libxext=1.3.4=h516909a_0
> xorg-libxfixes=5.0.3=h516909a_1004
> xorg-libxi=1.7.10=h516909a_0
> xorg-libxrender=0.9.10=h516909a_1002
> xorg-renderproto=0.11.1=h14c3975_1002
> xorg-xextproto=7.3.0=h14c3975_1002
> xorg-xproto=7.0.31=h14c3975_1007
> xz=5.2.4=h14c3975_4
> zlib=1.2.11=h7b6447c_3
> zstd=1.4.0=h3b9ef0a_0

2. try to make a new environment with
conda create --name "your envname" --file opencv_py37_conda-forge.txt -c conda-forge

3. conda activate "your envname"

4.  for Windows
pip install https://github.com/ai4ce/pyAprilTag/releases/download/0.0.6/pyAprilTag-0.0.6-cp37-cp37m-win_amd64.whl

for Ubuntu
pip install https://github.com/ai4ce/pyAprilTag/releases/download/0.0.6/pyAprilTag-0.0.6-cp37-cp37m-linux_x86_64.whl

5. try python -m pyAprilTag.demo

Let me know if this fixes the problem.

**Comment by mmgordon82** [comment]
It did.
Thx.
